# Generated by Django 4.0 on 2022-03-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_options_alter_comment_post_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status_comment',
            field=models.BooleanField(default=False, verbose_name='Статус коммента'),
        ),
    ]
